// Generated by nuxi
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@nuxt/content" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />

export {}
